export const countries = [
  { label: 'Afghanistan', id: 'AF', cc: '004' },
  { label: 'Åland Islands', id: 'AX', cc: '248' },
  { label: 'Albania', id: 'AL', cc: '008' },
  { label: 'Algeria', id: 'DZ', cc: '012' },
  { label: 'American Samoa', id: 'AS', cc: '016' },
  { label: 'Andorra', id: 'AD', cc: '020' },
  { label: 'Angola', id: 'AO', cc: '024' },
  { label: 'Anguilla', id: 'AI', cc: '660' },
  { label: 'Antarctica', id: 'AQ', cc: '010' },
  { label: 'Antigua and Barbuda', id: 'AG', cc: '028' },
  { label: 'Argentina', id: 'AR', cc: '032' },
  { label: 'Armenia', id: 'AM', cc: '051' },
  { label: 'Aruba', id: 'AW', cc: '533' },
  { label: 'Australia', id: 'AU', cc: '036' },
  { label: 'Austria', id: 'AT', cc: '040' },
  { label: 'Azerbaijan', id: 'AZ', cc: '031' },
  { label: 'Bahamas', id: 'BS', cc: '044' },
  { label: 'Bahrain', id: 'BH', cc: '048' },
  { label: 'Bangladesh', id: 'BD', cc: '050' },
  { label: 'Barbados', id: 'BB', cc: '052' },
  { label: 'Belarus', id: 'BY', cc: '112' },
  { label: 'Belgium', id: 'BE', cc: '056' },
  { label: 'Belize', id: 'BZ', cc: '084' },
  { label: 'Benin', id: 'BJ', cc: '204' },
  { label: 'Bermuda', id: 'BM', cc: '060' },
  { label: 'Bhutan', id: 'BT', cc: '064' },
  { label: 'Bolivia (Plurinational State of)', id: 'BO', cc: '068' },
  { label: 'Bonaire, Sint Eustatius and Saba', id: 'BQ', cc: '535' },
  { label: 'Bosnia and Herzegovina', id: 'BA', cc: '070' },
  { label: 'Botswana', id: 'BW', cc: '072' },
  { label: 'Bouvet Island', id: 'BV', cc: '074' },
  { label: 'Brazil', id: 'BR', cc: '076' },
  { label: 'British Indian Ocean Territory', id: 'IO', cc: '086' },
  { label: 'Brunei Darussalam', id: 'BN', cc: '096' },
  { label: 'Bulgaria', id: 'BG', cc: '100' },
  { label: 'Burkina Faso', id: 'BF', cc: '854' },
  { label: 'Burundi', id: 'BI', cc: '108' },
  { label: 'Cabo Verde', id: 'CV', cc: '132' },
  { label: 'Cambodia', id: 'KH', cc: '116' },
  { label: 'Cameroon', id: 'CM', cc: '120' },
  { label: 'Canada', id: 'CA', cc: '124' },
  { label: 'Cayman Islands', id: 'KY', cc: '136' },
  { label: 'Central African Republic', id: 'CF', cc: '140' },
  { label: 'Chad', id: 'TD', cc: '148' },
  { label: 'Chile', id: 'CL', cc: '152' },
  { label: 'China', id: 'CN', cc: '156' },
  { label: 'Christmas Island', id: 'CX', cc: '162' },
  { label: 'Cocos (Keeling) Islands', id: 'CC', cc: '166' },
  { label: 'Colombia', id: 'CO', cc: '170' },
  { label: 'Comoros', id: 'KM', cc: '174' },
  { label: 'Congo', id: 'CG', cc: '178' },
  { label: 'Congo, Democratic Republic of the', id: 'CD', cc: '180' },
  { label: 'Cook Islands', id: 'CK', cc: '184' },
  { label: 'Costa Rica', id: 'CR', cc: '188' },
  { label: "Côte d'Ivoire", id: 'CI', cc: '384' },
  { label: 'Croatia', id: 'HR', cc: '191' },
  { label: 'Cuba', id: 'CU', cc: '192' },
  { label: 'Curaçao', id: 'CW', cc: '531' },
  { label: 'Cyprus', id: 'CY', cc: '196' },
  { label: 'Czechia', id: 'CZ', cc: '203' },
  { label: 'Denmark', id: 'DK', cc: '208' },
  { label: 'Djibouti', id: 'DJ', cc: '262' },
  { label: 'Dominica', id: 'DM', cc: '212' },
  { label: 'Dominican Republic', id: 'DO', cc: '214' },
  { label: 'Ecuador', id: 'EC', cc: '218' },
  { label: 'Egypt', id: 'EG', cc: '818' },
  { label: 'El Salvador', id: 'SV', cc: '222' },
  { label: 'Equatorial Guinea', id: 'GQ', cc: '226' },
  { label: 'Eritrea', id: 'ER', cc: '232' },
  { label: 'Estonia', id: 'EE', cc: '233' },
  { label: 'Eswatini', id: 'SZ', cc: '748' },
  { label: 'Ethiopia', id: 'ET', cc: '231' },
  { label: 'Falkland Islands (Malvinas)', id: 'FK', cc: '238' },
  { label: 'Faroe Islands', id: 'FO', cc: '234' },
  { label: 'Fiji', id: 'FJ', cc: '242' },
  { label: 'Finland', id: 'FI', cc: '246' },
  { label: 'France', id: 'FR', cc: '250' },
  { label: 'French Guiana', id: 'GF', cc: '254' },
  { label: 'French Polynesia', id: 'PF', cc: '258' },
  { label: 'French Southern Territories', id: 'TF', cc: '260' },
  { label: 'Gabon', id: 'GA', cc: '266' },
  { label: 'Gambia', id: 'GM', cc: '270' },
  { label: 'Georgia', id: 'GE', cc: '268' },
  { label: 'Germany', id: 'DE', cc: '276' },
  { label: 'Ghana', id: 'GH', cc: '288' },
  { label: 'Gibraltar', id: 'GI', cc: '292' },
  { label: 'Greece', id: 'GR', cc: '300' },
  { label: 'Greenland', id: 'GL', cc: '304' },
  { label: 'Grenada', id: 'GD', cc: '308' },
  { label: 'Guadeloupe', id: 'GP', cc: '312' },
  { label: 'Guam', id: 'GU', cc: '316' },
  { label: 'Guatemala', id: 'GT', cc: '320' },
  { label: 'Guernsey', id: 'GG', cc: '831' },
  { label: 'Guinea', id: 'GN', cc: '324' },
  { label: 'Guinea-Bissau', id: 'GW', cc: '624' },
  { label: 'Guyana', id: 'GY', cc: '328' },
  { label: 'Haiti', id: 'HT', cc: '332' },
  { label: 'Heard Island and McDonald Islands', id: 'HM', cc: '334' },
  { label: 'Holy See', id: 'VA', cc: '336' },
  { label: 'Honduras', id: 'HN', cc: '340' },
  { label: 'Hong Kong', id: 'HK', cc: '344' },
  { label: 'Hungary', id: 'HU', cc: '348' },
  { label: 'Iceland', id: 'IS', cc: '352' },
  { label: 'India', id: 'IN', cc: '356' },
  { label: 'Indonesia', id: 'ID', cc: '360' },
  { label: 'Iran (Islamic Republic of)', id: 'IR', cc: '364' },
  { label: 'Iraq', id: 'IQ', cc: '368' },
  { label: 'Ireland', id: 'IE', cc: '372' },
  { label: 'Isle of Man', id: 'IM', cc: '833' },
  { label: 'Israel', id: 'IL', cc: '376' },
  { label: 'Italy', id: 'IT', cc: '380' },
  { label: 'Jamaica', id: 'JM', cc: '388' },
  { label: 'Japan', id: 'JP', cc: '392' },
  { label: 'Jersey', id: 'JE', cc: '832' },
  { label: 'Jordan', id: 'JO', cc: '400' },
  { label: 'Kazakhstan', id: 'KZ', cc: '398' },
  { label: 'Kenya', id: 'KE', cc: '404' },
  { label: 'Kiribati', id: 'KI', cc: '296' },
  { label: "Korea (Democratic People's Republic of)", id: 'KP', cc: '408' },
  { label: 'Korea, Republic of', id: 'KR', cc: '410' },
  { label: 'Kuwait', id: 'KW', cc: '414' },
  { label: 'Kyrgyzstan', id: 'KG', cc: '417' },
  { label: "Lao People's Democratic Republic", id: 'LA', cc: '418' },
  { label: 'Latvia', id: 'LV', cc: '428' },
  { label: 'Lebanon', id: 'LB', cc: '422' },
  { label: 'Lesotho', id: 'LS', cc: '426' },
  { label: 'Liberia', id: 'LR', cc: '430' },
  { label: 'Libya', id: 'LY', cc: '434' },
  { label: 'Liechtenstein', id: 'LI', cc: '438' },
  { label: 'Lithuania', id: 'LT', cc: '440' },
  { label: 'Luxembourg', id: 'LU', cc: '442' },
  { label: 'Macao', id: 'MO', cc: '446' },
  { label: 'Madagascar', id: 'MG', cc: '450' },
  { label: 'Malawi', id: 'MW', cc: '454' },
  { label: 'Malaysia', id: 'MY', cc: '458' },
  { label: 'Maldives', id: 'MV', cc: '462' },
  { label: 'Mali', id: 'ML', cc: '466' },
  { label: 'Malta', id: 'MT', cc: '470' },
  { label: 'Marshall Islands', id: 'MH', cc: '584' },
  { label: 'Martinique', id: 'MQ', cc: '474' },
  { label: 'Mauritania', id: 'MR', cc: '478' },
  { label: 'Mauritius', id: 'MU', cc: '480' },
  { label: 'Mayotte', id: 'YT', cc: '175' },
  { label: 'Mexico', id: 'MX', cc: '484' },
  { label: 'Micronesia (Federated States of)', id: 'FM', cc: '583' },
  { label: 'Moldova, Republic of', id: 'MD', cc: '498' },
  { label: 'Monaco', id: 'MC', cc: '492' },
  { label: 'Mongolia', id: 'MN', cc: '496' },
  { label: 'Montenegro', id: 'ME', cc: '499' },
  { label: 'Montserrat', id: 'MS', cc: '500' },
  { label: 'Morocco', id: 'MA', cc: '504' },
  { label: 'Mozambique', id: 'MZ', cc: '508' },
  { label: 'Myanmar', id: 'MM', cc: '104' },
  { label: 'Namibia', id: 'NA', cc: '516' },
  { label: 'Nauru', id: 'NR', cc: '520' },
  { label: 'Nepal', id: 'NP', cc: '524' },
  { label: 'Netherlands', id: 'NL', cc: '528' },
  { label: 'New Caledonia', id: 'NC', cc: '540' },
  { label: 'New Zealand', id: 'NZ', cc: '554' },
  { label: 'Nicaragua', id: 'NI', cc: '558' },
  { label: 'Niger', id: 'NE', cc: '562' },
  { label: 'Nigeria', id: 'NG', cc: '566' },
  { label: 'Niue', id: 'NU', cc: '570' },
  { label: 'Norfolk Island', id: 'NF', cc: '574' },
  { label: 'North Macedonia', id: 'MK', cc: '807' },
  { label: 'Northern Mariana Islands', id: 'MP', cc: '580' },
  { label: 'Norway', id: 'NO', cc: '578' },
  { label: 'Oman', id: 'OM', cc: '512' },
  { label: 'Pakistan', id: 'PK', cc: '586' },
  { label: 'Palau', id: 'PW', cc: '585' },
  { label: 'Palestine, State of', id: 'PS', cc: '275' },
  { label: 'Panama', id: 'PA', cc: '591' },
  { label: 'Papua New Guinea', id: 'PG', cc: '598' },
  { label: 'Paraguay', id: 'PY', cc: '600' },
  { label: 'Peru', id: 'PE', cc: '604' },
  { label: 'Philippines', id: 'PH', cc: '608' },
  { label: 'Pitcairn', id: 'PN', cc: '612' },
  { label: 'Poland', id: 'PL', cc: '616' },
  { label: 'Portugal', id: 'PT', cc: '620' },
  { label: 'Puerto Rico', id: 'PR', cc: '630' },
  { label: 'Qatar', id: 'QA', cc: '634' },
  { label: 'Réunion', id: 'RE', cc: '638' },
  { label: 'Romania', id: 'RO', cc: '642' },
  { label: 'Russian Federation', id: 'RU', cc: '643' },
  { label: 'Rwanda', id: 'RW', cc: '646' },
  { label: 'Saint Barthélemy', id: 'BL', cc: '652' },
  { label: 'Saint Helena, Ascension and Tristan da Cunha', id: 'SH', cc: '654' },
  { label: 'Saint Kitts and Nevis', id: 'KN', cc: '659' },
  { label: 'Saint Lucia', id: 'LC', cc: '662' },
  { label: 'Saint Martin (French part)', id: 'MF', cc: '663' },
  { label: 'Saint Pierre and Miquelon', id: 'PM', cc: '666' },
  { label: 'Saint Vincent and the Grenadines', id: 'VC', cc: '670' },
  { label: 'Samoa', id: 'WS', cc: '882' },
  { label: 'San Marino', id: 'SM', cc: '674' },
  { label: 'Sao Tome and Principe', id: 'ST', cc: '678' },
  { label: 'Saudi Arabia', id: 'SA', cc: '682' },
  { label: 'Senegal', id: 'SN', cc: '686' },
  { label: 'Serbia', id: 'RS', cc: '688' },
  { label: 'Seychelles', id: 'SC', cc: '690' },
  { label: 'Sierra Leone', id: 'SL', cc: '694' },
  { label: 'Singapore', id: 'SG', cc: '702' },
  { label: 'Sint Maarten (Dutch part)', id: 'SX', cc: '534' },
  { label: 'Slovakia', id: 'SK', cc: '703' },
  { label: 'Slovenia', id: 'SI', cc: '705' },
  { label: 'Solomon Islands', id: 'SB', cc: '090' },
  { label: 'Somalia', id: 'SO', cc: '706' },
  { label: 'South Africa', id: 'ZA', cc: '710' },
  { label: 'South Georgia and the South Sandwich Islands', id: 'GS', cc: '239' },
  { label: 'South Sudan', id: 'SS', cc: '728' },
  { label: 'Spain', id: 'ES', cc: '724' },
  { label: 'Sri Lanka', id: 'LK', cc: '144' },
  { label: 'Sudan', id: 'SD', cc: '729' },
  { label: 'Surilabel', id: 'SR', cc: '740' },
  { label: 'Svalbard and Jan Mayen', id: 'SJ', cc: '744' },
  { label: 'Sweden', id: 'SE', cc: '752' },
  { label: 'Switzerland', id: 'CH', cc: '756' },
  { label: 'Syrian Arab Republic', id: 'SY', cc: '760' },
  { label: 'Taiwan, Province of China', id: 'TW', cc: '158' },
  { label: 'Tajikistan', id: 'TJ', cc: '762' },
  { label: 'Tanzania, United Republic of', id: 'TZ', cc: '834' },
  { label: 'Thailand', id: 'TH', cc: '764' },
  { label: 'Timor-Leste', id: 'TL', cc: '626' },
  { label: 'Togo', id: 'TG', cc: '768' },
  { label: 'Tokelau', id: 'TK', cc: '772' },
  { label: 'Tonga', id: 'TO', cc: '776' },
  { label: 'Trinidad and Tobago', id: 'TT', cc: '780' },
  { label: 'Tunisia', id: 'TN', cc: '788' },
  { label: 'Turkey', id: 'TR', cc: '792' },
  { label: 'Turkmenistan', id: 'TM', cc: '795' },
  { label: 'Turks and Caicos Islands', id: 'TC', cc: '796' },
  { label: 'Tuvalu', id: 'TV', cc: '798' },
  { label: 'Uganda', id: 'UG', cc: '800' },
  { label: 'Ukraine', id: 'UA', cc: '804' },
  { label: 'United Arab Emirates', id: 'AE', cc: '784' },
  {
    label: 'United Kingdom of Great Britain and Northern Ireland',
    id: 'GB',
    cc: '826',
  },
  { label: 'United States of America', id: 'US', cc: '840' },
  { label: 'United States Minor Outlying Islands', id: 'UM', cc: '581' },
  { label: 'Uruguay', id: 'UY', cc: '858' },
  { label: 'Uzbekistan', id: 'UZ', cc: '860' },
  { label: 'Vanuatu', id: 'VU', cc: '548' },
  { label: 'Venezuela (Bolivarian Republic of)', id: 'VE', cc: '862' },
  { label: 'Viet Nam', id: 'VN', cc: '704' },
  { label: 'Virgin Islands (British)', id: 'VG', cc: '092' },
  { label: 'Virgin Islands (U.S.)', id: 'VI', cc: '850' },
  { label: 'Wallis and Futuna', id: 'WF', cc: '876' },
  { label: 'Western Sahara', id: 'EH', cc: '732' },
  { label: 'Yemen', id: 'YE', cc: '887' },
  { label: 'Zambia', id: 'ZM', cc: '894' },
  { label: 'Zimbabwe', id: 'ZW', cc: '716' },
];
